/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AAtribuicaoSemSubComando extends PSemSubComando
{
    private PComandoAtribuicao _atrib_;
    private TPVirg _pVirg_;

    public AAtribuicaoSemSubComando()
    {
        // Constructor
    }

    public AAtribuicaoSemSubComando(
        @SuppressWarnings("hiding") PComandoAtribuicao _atrib_,
        @SuppressWarnings("hiding") TPVirg _pVirg_)
    {
        // Constructor
        setAtrib(_atrib_);

        setPVirg(_pVirg_);

    }

    @Override
    public Object clone()
    {
        return new AAtribuicaoSemSubComando(
            cloneNode(this._atrib_),
            cloneNode(this._pVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribuicaoSemSubComando(this);
    }

    public PComandoAtribuicao getAtrib()
    {
        return this._atrib_;
    }

    public void setAtrib(PComandoAtribuicao node)
    {
        if(this._atrib_ != null)
        {
            this._atrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atrib_ = node;
    }

    public TPVirg getPVirg()
    {
        return this._pVirg_;
    }

    public void setPVirg(TPVirg node)
    {
        if(this._pVirg_ != null)
        {
            this._pVirg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pVirg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atrib_)
            + toString(this._pVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atrib_ == child)
        {
            this._atrib_ = null;
            return;
        }

        if(this._pVirg_ == child)
        {
            this._pVirg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atrib_ == oldChild)
        {
            setAtrib((PComandoAtribuicao) newChild);
            return;
        }

        if(this._pVirg_ == oldChild)
        {
            setPVirg((TPVirg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
