/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AAvaloradoTipo extends PTipo
{
    private PTipoAvalorado _tipoAvalorado_;

    public AAvaloradoTipo()
    {
        // Constructor
    }

    public AAvaloradoTipo(
        @SuppressWarnings("hiding") PTipoAvalorado _tipoAvalorado_)
    {
        // Constructor
        setTipoAvalorado(_tipoAvalorado_);

    }

    @Override
    public Object clone()
    {
        return new AAvaloradoTipo(
            cloneNode(this._tipoAvalorado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAvaloradoTipo(this);
    }

    public PTipoAvalorado getTipoAvalorado()
    {
        return this._tipoAvalorado_;
    }

    public void setTipoAvalorado(PTipoAvalorado node)
    {
        if(this._tipoAvalorado_ != null)
        {
            this._tipoAvalorado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoAvalorado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoAvalorado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoAvalorado_ == child)
        {
            this._tipoAvalorado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoAvalorado_ == oldChild)
        {
            setTipoAvalorado((PTipoAvalorado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
