/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AComandoRetorno extends PComandoRetorno
{
    private TPChaveReturn _pChaveReturn_;
    private PExpGeral _expGeral_;

    public AComandoRetorno()
    {
        // Constructor
    }

    public AComandoRetorno(
        @SuppressWarnings("hiding") TPChaveReturn _pChaveReturn_,
        @SuppressWarnings("hiding") PExpGeral _expGeral_)
    {
        // Constructor
        setPChaveReturn(_pChaveReturn_);

        setExpGeral(_expGeral_);

    }

    @Override
    public Object clone()
    {
        return new AComandoRetorno(
            cloneNode(this._pChaveReturn_),
            cloneNode(this._expGeral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoRetorno(this);
    }

    public TPChaveReturn getPChaveReturn()
    {
        return this._pChaveReturn_;
    }

    public void setPChaveReturn(TPChaveReturn node)
    {
        if(this._pChaveReturn_ != null)
        {
            this._pChaveReturn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pChaveReturn_ = node;
    }

    public PExpGeral getExpGeral()
    {
        return this._expGeral_;
    }

    public void setExpGeral(PExpGeral node)
    {
        if(this._expGeral_ != null)
        {
            this._expGeral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expGeral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pChaveReturn_)
            + toString(this._expGeral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pChaveReturn_ == child)
        {
            this._pChaveReturn_ = null;
            return;
        }

        if(this._expGeral_ == child)
        {
            this._expGeral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pChaveReturn_ == oldChild)
        {
            setPChaveReturn((TPChaveReturn) newChild);
            return;
        }

        if(this._expGeral_ == oldChild)
        {
            setExpGeral((PExpGeral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
