/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class ACondicaoElseComando extends PComando
{
    private PComandoCondicaoElse _comandoCondicaoElse_;

    public ACondicaoElseComando()
    {
        // Constructor
    }

    public ACondicaoElseComando(
        @SuppressWarnings("hiding") PComandoCondicaoElse _comandoCondicaoElse_)
    {
        // Constructor
        setComandoCondicaoElse(_comandoCondicaoElse_);

    }

    @Override
    public Object clone()
    {
        return new ACondicaoElseComando(
            cloneNode(this._comandoCondicaoElse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicaoElseComando(this);
    }

    public PComandoCondicaoElse getComandoCondicaoElse()
    {
        return this._comandoCondicaoElse_;
    }

    public void setComandoCondicaoElse(PComandoCondicaoElse node)
    {
        if(this._comandoCondicaoElse_ != null)
        {
            this._comandoCondicaoElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoCondicaoElse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoCondicaoElse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoCondicaoElse_ == child)
        {
            this._comandoCondicaoElse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoCondicaoElse_ == oldChild)
        {
            setComandoCondicaoElse((PComandoCondicaoElse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
