/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class ACondicaoElseIfNaoCurtoComandoIfNaoCurto extends PComandoIfNaoCurto
{
    private PComandoCondicaoElseIfNaoCurto _comandoCondicaoElseIfNaoCurto_;

    public ACondicaoElseIfNaoCurtoComandoIfNaoCurto()
    {
        // Constructor
    }

    public ACondicaoElseIfNaoCurtoComandoIfNaoCurto(
        @SuppressWarnings("hiding") PComandoCondicaoElseIfNaoCurto _comandoCondicaoElseIfNaoCurto_)
    {
        // Constructor
        setComandoCondicaoElseIfNaoCurto(_comandoCondicaoElseIfNaoCurto_);

    }

    @Override
    public Object clone()
    {
        return new ACondicaoElseIfNaoCurtoComandoIfNaoCurto(
            cloneNode(this._comandoCondicaoElseIfNaoCurto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicaoElseIfNaoCurtoComandoIfNaoCurto(this);
    }

    public PComandoCondicaoElseIfNaoCurto getComandoCondicaoElseIfNaoCurto()
    {
        return this._comandoCondicaoElseIfNaoCurto_;
    }

    public void setComandoCondicaoElseIfNaoCurto(PComandoCondicaoElseIfNaoCurto node)
    {
        if(this._comandoCondicaoElseIfNaoCurto_ != null)
        {
            this._comandoCondicaoElseIfNaoCurto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoCondicaoElseIfNaoCurto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoCondicaoElseIfNaoCurto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoCondicaoElseIfNaoCurto_ == child)
        {
            this._comandoCondicaoElseIfNaoCurto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoCondicaoElseIfNaoCurto_ == oldChild)
        {
            setComandoCondicaoElseIfNaoCurto((PComandoCondicaoElseIfNaoCurto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
