/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoSemSubComando extends PSemSubComando
{
    private PDeclVariavel _decl_;
    private TPVirg _pVirg_;

    public ADeclaracaoSemSubComando()
    {
        // Constructor
    }

    public ADeclaracaoSemSubComando(
        @SuppressWarnings("hiding") PDeclVariavel _decl_,
        @SuppressWarnings("hiding") TPVirg _pVirg_)
    {
        // Constructor
        setDecl(_decl_);

        setPVirg(_pVirg_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoSemSubComando(
            cloneNode(this._decl_),
            cloneNode(this._pVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoSemSubComando(this);
    }

    public PDeclVariavel getDecl()
    {
        return this._decl_;
    }

    public void setDecl(PDeclVariavel node)
    {
        if(this._decl_ != null)
        {
            this._decl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decl_ = node;
    }

    public TPVirg getPVirg()
    {
        return this._pVirg_;
    }

    public void setPVirg(TPVirg node)
    {
        if(this._pVirg_ != null)
        {
            this._pVirg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pVirg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decl_)
            + toString(this._pVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decl_ == child)
        {
            this._decl_ = null;
            return;
        }

        if(this._pVirg_ == child)
        {
            this._pVirg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decl_ == oldChild)
        {
            setDecl((PDeclVariavel) newChild);
            return;
        }

        if(this._pVirg_ == oldChild)
        {
            setPVirg((TPVirg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
