/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class ADeclMatrizIntComando extends PComando
{
    private TId _nome_;
    private TNum _dimen_;

    public ADeclMatrizIntComando()
    {
        // Constructor
    }

    public ADeclMatrizIntComando(
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") TNum _dimen_)
    {
        // Constructor
        setNome(_nome_);

        setDimen(_dimen_);

    }

    @Override
    public Object clone()
    {
        return new ADeclMatrizIntComando(
            cloneNode(this._nome_),
            cloneNode(this._dimen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclMatrizIntComando(this);
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public TNum getDimen()
    {
        return this._dimen_;
    }

    public void setDimen(TNum node)
    {
        if(this._dimen_ != null)
        {
            this._dimen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dimen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nome_)
            + toString(this._dimen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._dimen_ == child)
        {
            this._dimen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        if(this._dimen_ == oldChild)
        {
            setDimen((TNum) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
