/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaoDeclaracao extends PDeclaracao
{
    private PDeclFuncao _declFuncao_;

    public AFuncaoDeclaracao()
    {
        // Constructor
    }

    public AFuncaoDeclaracao(
        @SuppressWarnings("hiding") PDeclFuncao _declFuncao_)
    {
        // Constructor
        setDeclFuncao(_declFuncao_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaoDeclaracao(
            cloneNode(this._declFuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaoDeclaracao(this);
    }

    public PDeclFuncao getDeclFuncao()
    {
        return this._declFuncao_;
    }

    public void setDeclFuncao(PDeclFuncao node)
    {
        if(this._declFuncao_ != null)
        {
            this._declFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declFuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declFuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declFuncao_ == child)
        {
            this._declFuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declFuncao_ == oldChild)
        {
            setDeclFuncao((PDeclFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
