/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AFuncaoSemSubComando extends PSemSubComando
{
    private PComandoFuncao _func_;
    private TPVirg _pVirg_;

    public AFuncaoSemSubComando()
    {
        // Constructor
    }

    public AFuncaoSemSubComando(
        @SuppressWarnings("hiding") PComandoFuncao _func_,
        @SuppressWarnings("hiding") TPVirg _pVirg_)
    {
        // Constructor
        setFunc(_func_);

        setPVirg(_pVirg_);

    }

    @Override
    public Object clone()
    {
        return new AFuncaoSemSubComando(
            cloneNode(this._func_),
            cloneNode(this._pVirg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFuncaoSemSubComando(this);
    }

    public PComandoFuncao getFunc()
    {
        return this._func_;
    }

    public void setFunc(PComandoFuncao node)
    {
        if(this._func_ != null)
        {
            this._func_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._func_ = node;
    }

    public TPVirg getPVirg()
    {
        return this._pVirg_;
    }

    public void setPVirg(TPVirg node)
    {
        if(this._pVirg_ != null)
        {
            this._pVirg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pVirg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._func_)
            + toString(this._pVirg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._func_ == child)
        {
            this._func_ = null;
            return;
        }

        if(this._pVirg_ == child)
        {
            this._pVirg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._func_ == oldChild)
        {
            setFunc((PComandoFuncao) newChild);
            return;
        }

        if(this._pVirg_ == oldChild)
        {
            setPVirg((TPVirg) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
