/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AIntTipoValorado extends PTipoValorado
{
    private TPChaveInt _pChaveInt_;

    public AIntTipoValorado()
    {
        // Constructor
    }

    public AIntTipoValorado(
        @SuppressWarnings("hiding") TPChaveInt _pChaveInt_)
    {
        // Constructor
        setPChaveInt(_pChaveInt_);

    }

    @Override
    public Object clone()
    {
        return new AIntTipoValorado(
            cloneNode(this._pChaveInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntTipoValorado(this);
    }

    public TPChaveInt getPChaveInt()
    {
        return this._pChaveInt_;
    }

    public void setPChaveInt(TPChaveInt node)
    {
        if(this._pChaveInt_ != null)
        {
            this._pChaveInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pChaveInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pChaveInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pChaveInt_ == child)
        {
            this._pChaveInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pChaveInt_ == oldChild)
        {
            setPChaveInt((TPChaveInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
