/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AListaSeqDeclParametro extends PSeqDeclParametro
{
    private PSeqDeclParametro _params_;
    private TVirg _virg_;
    private PDeclParametro _param_;

    public AListaSeqDeclParametro()
    {
        // Constructor
    }

    public AListaSeqDeclParametro(
        @SuppressWarnings("hiding") PSeqDeclParametro _params_,
        @SuppressWarnings("hiding") TVirg _virg_,
        @SuppressWarnings("hiding") PDeclParametro _param_)
    {
        // Constructor
        setParams(_params_);

        setVirg(_virg_);

        setParam(_param_);

    }

    @Override
    public Object clone()
    {
        return new AListaSeqDeclParametro(
            cloneNode(this._params_),
            cloneNode(this._virg_),
            cloneNode(this._param_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaSeqDeclParametro(this);
    }

    public PSeqDeclParametro getParams()
    {
        return this._params_;
    }

    public void setParams(PSeqDeclParametro node)
    {
        if(this._params_ != null)
        {
            this._params_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._params_ = node;
    }

    public TVirg getVirg()
    {
        return this._virg_;
    }

    public void setVirg(TVirg node)
    {
        if(this._virg_ != null)
        {
            this._virg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virg_ = node;
    }

    public PDeclParametro getParam()
    {
        return this._param_;
    }

    public void setParam(PDeclParametro node)
    {
        if(this._param_ != null)
        {
            this._param_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._param_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._params_)
            + toString(this._virg_)
            + toString(this._param_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._params_ == child)
        {
            this._params_ = null;
            return;
        }

        if(this._virg_ == child)
        {
            this._virg_ = null;
            return;
        }

        if(this._param_ == child)
        {
            this._param_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._params_ == oldChild)
        {
            setParams((PSeqDeclParametro) newChild);
            return;
        }

        if(this._virg_ == oldChild)
        {
            setVirg((TVirg) newChild);
            return;
        }

        if(this._param_ == oldChild)
        {
            setParam((PDeclParametro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
