/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AMatrizComandoAtribuicao extends PComandoAtribuicao
{
    private TId _nome_;
    private TACol _aCol_;
    private PSeqParametro _indices_;
    private TFCol _fCol_;
    private TAtrib _atrib_;
    private PExpGeral _valor_;

    public AMatrizComandoAtribuicao()
    {
        // Constructor
    }

    public AMatrizComandoAtribuicao(
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") TACol _aCol_,
        @SuppressWarnings("hiding") PSeqParametro _indices_,
        @SuppressWarnings("hiding") TFCol _fCol_,
        @SuppressWarnings("hiding") TAtrib _atrib_,
        @SuppressWarnings("hiding") PExpGeral _valor_)
    {
        // Constructor
        setNome(_nome_);

        setACol(_aCol_);

        setIndices(_indices_);

        setFCol(_fCol_);

        setAtrib(_atrib_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AMatrizComandoAtribuicao(
            cloneNode(this._nome_),
            cloneNode(this._aCol_),
            cloneNode(this._indices_),
            cloneNode(this._fCol_),
            cloneNode(this._atrib_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMatrizComandoAtribuicao(this);
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public TACol getACol()
    {
        return this._aCol_;
    }

    public void setACol(TACol node)
    {
        if(this._aCol_ != null)
        {
            this._aCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aCol_ = node;
    }

    public PSeqParametro getIndices()
    {
        return this._indices_;
    }

    public void setIndices(PSeqParametro node)
    {
        if(this._indices_ != null)
        {
            this._indices_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._indices_ = node;
    }

    public TFCol getFCol()
    {
        return this._fCol_;
    }

    public void setFCol(TFCol node)
    {
        if(this._fCol_ != null)
        {
            this._fCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fCol_ = node;
    }

    public TAtrib getAtrib()
    {
        return this._atrib_;
    }

    public void setAtrib(TAtrib node)
    {
        if(this._atrib_ != null)
        {
            this._atrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atrib_ = node;
    }

    public PExpGeral getValor()
    {
        return this._valor_;
    }

    public void setValor(PExpGeral node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nome_)
            + toString(this._aCol_)
            + toString(this._indices_)
            + toString(this._fCol_)
            + toString(this._atrib_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._aCol_ == child)
        {
            this._aCol_ = null;
            return;
        }

        if(this._indices_ == child)
        {
            this._indices_ = null;
            return;
        }

        if(this._fCol_ == child)
        {
            this._fCol_ = null;
            return;
        }

        if(this._atrib_ == child)
        {
            this._atrib_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        if(this._aCol_ == oldChild)
        {
            setACol((TACol) newChild);
            return;
        }

        if(this._indices_ == oldChild)
        {
            setIndices((PSeqParametro) newChild);
            return;
        }

        if(this._fCol_ == oldChild)
        {
            setFCol((TFCol) newChild);
            return;
        }

        if(this._atrib_ == oldChild)
        {
            setAtrib((TAtrib) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PExpGeral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
