/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AMatrizDeclVariavel extends PDeclVariavel
{
    private PTipoValorado _tipo_;
    private TId _nome_;
    private TACol _aCol_;
    private PSeqParametro _dimens_;
    private TFCol _fCol_;

    public AMatrizDeclVariavel()
    {
        // Constructor
    }

    public AMatrizDeclVariavel(
        @SuppressWarnings("hiding") PTipoValorado _tipo_,
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") TACol _aCol_,
        @SuppressWarnings("hiding") PSeqParametro _dimens_,
        @SuppressWarnings("hiding") TFCol _fCol_)
    {
        // Constructor
        setTipo(_tipo_);

        setNome(_nome_);

        setACol(_aCol_);

        setDimens(_dimens_);

        setFCol(_fCol_);

    }

    @Override
    public Object clone()
    {
        return new AMatrizDeclVariavel(
            cloneNode(this._tipo_),
            cloneNode(this._nome_),
            cloneNode(this._aCol_),
            cloneNode(this._dimens_),
            cloneNode(this._fCol_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMatrizDeclVariavel(this);
    }

    public PTipoValorado getTipo()
    {
        return this._tipo_;
    }

    public void setTipo(PTipoValorado node)
    {
        if(this._tipo_ != null)
        {
            this._tipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipo_ = node;
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public TACol getACol()
    {
        return this._aCol_;
    }

    public void setACol(TACol node)
    {
        if(this._aCol_ != null)
        {
            this._aCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aCol_ = node;
    }

    public PSeqParametro getDimens()
    {
        return this._dimens_;
    }

    public void setDimens(PSeqParametro node)
    {
        if(this._dimens_ != null)
        {
            this._dimens_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dimens_ = node;
    }

    public TFCol getFCol()
    {
        return this._fCol_;
    }

    public void setFCol(TFCol node)
    {
        if(this._fCol_ != null)
        {
            this._fCol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fCol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipo_)
            + toString(this._nome_)
            + toString(this._aCol_)
            + toString(this._dimens_)
            + toString(this._fCol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipo_ == child)
        {
            this._tipo_ = null;
            return;
        }

        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._aCol_ == child)
        {
            this._aCol_ = null;
            return;
        }

        if(this._dimens_ == child)
        {
            this._dimens_ = null;
            return;
        }

        if(this._fCol_ == child)
        {
            this._fCol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipo_ == oldChild)
        {
            setTipo((PTipoValorado) newChild);
            return;
        }

        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        if(this._aCol_ == oldChild)
        {
            setACol((TACol) newChild);
            return;
        }

        if(this._dimens_ == oldChild)
        {
            setDimens((PSeqParametro) newChild);
            return;
        }

        if(this._fCol_ == oldChild)
        {
            setFCol((TFCol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
