/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AOpSomaExp extends PExp
{
    private PExp _esq_;
    private POpSoma _opSoma_;
    private PTermo _dir_;

    public AOpSomaExp()
    {
        // Constructor
    }

    public AOpSomaExp(
        @SuppressWarnings("hiding") PExp _esq_,
        @SuppressWarnings("hiding") POpSoma _opSoma_,
        @SuppressWarnings("hiding") PTermo _dir_)
    {
        // Constructor
        setEsq(_esq_);

        setOpSoma(_opSoma_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new AOpSomaExp(
            cloneNode(this._esq_),
            cloneNode(this._opSoma_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpSomaExp(this);
    }

    public PExp getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PExp node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public POpSoma getOpSoma()
    {
        return this._opSoma_;
    }

    public void setOpSoma(POpSoma node)
    {
        if(this._opSoma_ != null)
        {
            this._opSoma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opSoma_ = node;
    }

    public PTermo getDir()
    {
        return this._dir_;
    }

    public void setDir(PTermo node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esq_)
            + toString(this._opSoma_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._opSoma_ == child)
        {
            this._opSoma_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esq_ == oldChild)
        {
            setEsq((PExp) newChild);
            return;
        }

        if(this._opSoma_ == oldChild)
        {
            setOpSoma((POpSoma) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
