/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class ARepeticaoComando extends PComando
{
    private PComandoRepeticao _comandoRepeticao_;

    public ARepeticaoComando()
    {
        // Constructor
    }

    public ARepeticaoComando(
        @SuppressWarnings("hiding") PComandoRepeticao _comandoRepeticao_)
    {
        // Constructor
        setComandoRepeticao(_comandoRepeticao_);

    }

    @Override
    public Object clone()
    {
        return new ARepeticaoComando(
            cloneNode(this._comandoRepeticao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARepeticaoComando(this);
    }

    public PComandoRepeticao getComandoRepeticao()
    {
        return this._comandoRepeticao_;
    }

    public void setComandoRepeticao(PComandoRepeticao node)
    {
        if(this._comandoRepeticao_ != null)
        {
            this._comandoRepeticao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoRepeticao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoRepeticao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoRepeticao_ == child)
        {
            this._comandoRepeticao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoRepeticao_ == oldChild)
        {
            setComandoRepeticao((PComandoRepeticao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
