/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class AVariavelComandoAtribuicao extends PComandoAtribuicao
{
    private TId _nome_;
    private TAtrib _atrib_;
    private PExpGeral _valor_;

    public AVariavelComandoAtribuicao()
    {
        // Constructor
    }

    public AVariavelComandoAtribuicao(
        @SuppressWarnings("hiding") TId _nome_,
        @SuppressWarnings("hiding") TAtrib _atrib_,
        @SuppressWarnings("hiding") PExpGeral _valor_)
    {
        // Constructor
        setNome(_nome_);

        setAtrib(_atrib_);

        setValor(_valor_);

    }

    @Override
    public Object clone()
    {
        return new AVariavelComandoAtribuicao(
            cloneNode(this._nome_),
            cloneNode(this._atrib_),
            cloneNode(this._valor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariavelComandoAtribuicao(this);
    }

    public TId getNome()
    {
        return this._nome_;
    }

    public void setNome(TId node)
    {
        if(this._nome_ != null)
        {
            this._nome_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nome_ = node;
    }

    public TAtrib getAtrib()
    {
        return this._atrib_;
    }

    public void setAtrib(TAtrib node)
    {
        if(this._atrib_ != null)
        {
            this._atrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atrib_ = node;
    }

    public PExpGeral getValor()
    {
        return this._valor_;
    }

    public void setValor(PExpGeral node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nome_)
            + toString(this._atrib_)
            + toString(this._valor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nome_ == child)
        {
            this._nome_ = null;
            return;
        }

        if(this._atrib_ == child)
        {
            this._atrib_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nome_ == oldChild)
        {
            setNome((TId) newChild);
            return;
        }

        if(this._atrib_ == oldChild)
        {
            setAtrib((TAtrib) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PExpGeral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
