/* This file was generated by SableCC (http://www.sablecc.org/). */

package compiladorCMenos.node;

import compiladorCMenos.analysis.*;

@SuppressWarnings("nls")
public final class TPChaveWhile extends Token
{
    public TPChaveWhile()
    {
        super.setText("while");
    }

    public TPChaveWhile(int line, int pos)
    {
        super.setText("while");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPChaveWhile(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPChaveWhile(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPChaveWhile text.");
    }
}
